
CREATE PROC GetTitleAndCopies @Title VARCHAR(50)
AS

SELECT BK.Title, BC.No_Of_Copies --LB.BranchName, BA.AuthorName 
FROM BOOK AS BK
INNER JOIN BOOK_AUTHORS AS BA
ON BK.BookId = BA.BookId
INNER JOIN BOOK_COPIES AS BC
ON BK.BookId = BC.BookId
INNER JOIN LIBRARY_BRANCH AS LB 
ON LB.BranchId = BC.BranchId
WHERE BK.Title = @Title