INSERT INTO BOOK_LOANS VALUES (5,'2','2','5/1/05','6/1/05')
INSERT INTO BOOK_LOANS VALUES (6,'2','2','5/1/05','6/1/05')
INSERT INTO BOOK_LOANS VALUES (7,'2','2','5/1/05','6/1/05')
INSERT INTO BOOK_LOANS VALUES (8,'2','2','5/1/05','6/1/05')
update BOOK_LOANS VALUES (10,'2','2','5/1/05','6/1/05')

UPDATE BOOK_LOANS
SET BranchId = '2'
WHERE BookID = 10

SELECT * FROM BOOK
SELECT * FROM BOOK_COPIES
SELECT * FROM BORROWER
SELECT * FROM BOOK_LOANS
INSERT INTO LIBRARY_BRANCH VALUES (4,'Redwood','123 Main St')


INSERT INTO BOOK_AUTHORS VALUES (2,'Mark Lee')
INSERT INTO BOOK_AUTHORS VALUES (3,'Mark Lee')
INSERT INTO BOOK_AUTHORS VALUES (4,'Mark Lee')
INSERT INTO BOOK_AUTHORS VALUES (5,'Mark Lee')
INSERT INTO BOOK_AUTHORS VALUES (6,'Mark Lee')
INSERT INTO BOOK_AUTHORS VALUES (7,'Mark Lee')
INSERT INTO BOOK_AUTHORS VALUES (8,'Mark Lee')
INSERT INTO BOOK_AUTHORS VALUES (9,'Mark Lee')
INSERT INTO BOOK_AUTHORS VALUES (10,'Stephen King')


INSERT INTO BOOK VALUES (3,'The Lost Tribe','Mark Williams')
INSERT INTO BOOK VALUES (4,'The Lost Tribe','Mark Williams')
INSERT INTO BOOK VALUES (5,'The Lost Tribe','Mark Williams')
INSERT INTO BOOK VALUES (6,'The Lost Tribe','Mark Williams')
INSERT INTO BOOK VALUES (7,'The Lost Tribe','Mark Williams')
INSERT INTO BOOK VALUES (8,'The Lost Tribe','Mark Williams')
INSERT INTO BOOK VALUES (9,'The Lost Tribe','Mark Williams')
INSERT INTO BOOK_COPIES VALUES (10,'The Lost Tribe','Mark Williams')
INSERT INTO BOOK VALUES (11,'The Lost Tribe','Mark Williams')
INSERT INTO BOOK VALUES (12,'The Lost Tribe','Mark Williams')
INSERT INTO BOOK VALUES (13,'The Lost Tribe','Mark Williams')
INSERT INTO BOOK VALUES (14,'The Lost Tribe','Mark Williams')
INSERT INTO BOOK VALUES (15,'The Lost Tribe','Mark Williams')
INSERT INTO BOOK VALUES (16,'The Lost Tribe','Mark Williams')
INSERT INTO BOOK VALUES (17,'The Lost Tribe','Mark Williams')
INSERT INTO BOOK VALUES (18,'The Lost Tribe','Mark Williams')
INSERT INTO BOOK VALUES (19,'The Lost Tribe','Mark Williams')
INSERT INTO BOOK VALUES (20,'The Dark Tower','Stephen King')

SELECT * FROM BOOK_AUTHORS